### ISSUE TITLE
Semantics test for `image_status`

### ISSUE THREAD

**Issue by ngeorge1098** [BerkeleyLab/llvm-project#22]

**Comment by ktras** [comment]
In progress on branch [image_status-add-semantics-test](https://github.com/BerkeleyLab/llvm-project/tree/image_status-add-semantics-test). Not yet ready to open differential. Need to add an additional check on one of the arguments.

**Comment by ngeorge1098** [comment]
[Differential 128009](https://reviews.llvm.org/D128009) is opened.

**Comment by ktras** [comment]
The closing of [Differential 128009](https://reviews.llvm.org/D128009) closes issue #22.
