### ISSUE TITLE
Semantics test for `stopped_images`

### ISSUE THREAD

**Issue by ktras** [BerkeleyLab/llvm-project#8]

**Comment by ngeorge1098** [comment]
[Differential D129513](https://reviews.llvm.org/D129513) is open.

**Comment by ktras** [comment]
[Differential D129513](https://reviews.llvm.org/D129513) and commit [6ac30fa6e941186](https://github.com/llvm/llvm-project/commit/6ac30fa6e94118613fd27f0fd896a86852eeea7a) closes issue #8.
